# Generated by Django 5.2.7 on 2025-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0002_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('number', 'album'), name='uniq_album_track_number'),
        ),
    ]
